version: "3"
services:
  pg_container:
    image: postgres:11.1-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  hardcover:
    image: hardcover
    container_name: hardcover
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/hardcover
    environment:
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY}
      - FLASK_ENV=${FLASK_ENV}
      - APPLICATION_MODE=${APPLICATION_MODE}
    command: bash start.sh
    expose:
      - 5000
    ports:
      - 5000:5000
    depends_on:
      - pg_container

volumes:
  volumes: {}
