version: "3"
networks:
  my-postgres:
    driver: bridge
  
services:
  pg_container:
    image: postgres:11.1-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  hardcover:
    image: hardcover
    container_name: hardcover
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    environment:
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY}
      - FLASK_ENV=${FLASK_ENV}
    ports:
      - 5000:5000
    depends_on:
      - pg_container

volumes:
  volumes:
