version: 2
jobs:
  backend_build:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: Install postgres
          command: |
            sudo apt-get -y update
            sudo apt-get install postgresql
  backend_test:
    docker:
      - image: circleci/python:3.7
    environment:
      FLASK_SECRET_KEY: faketestkey
    steps:
      - checkout
      - run:
          name: Install dependancies, run tests and generate code coverage
          command: |
            virtualenv venv
            source venv/bin/activate
            pip install -r requirements.txt
            pytest
            coverage run -m pytest
            coverage html

workflows:
  version: 2
  build-and-test:
    jobs:
      - backend_build
      - backend_test:
          requires:
            - backend_build
          filters:
            branches:
              only: develop
