version: 2
jobs:
  backend_test:
    docker:
      - image: circleci/python:3.7
    environment:
      FLASK_SECRET_KEY: faketestkey
    steps:
      - checkout
      - run:
          name: Install postgres
          command: |
            sudo apt-get -y update && sudo apt-get install postgresql
      - run:
          name: install dependencies and run tests
          command: |
            virtualenv venv
            source venv/bin/activate
            pip install -r requirements.txt 
            pytest
workflows:
  version: 2
  build-test:
    jobs:
      - backend_format
      - backend_test
