"""empty message

Revision ID: c66718b9c411
Revises: c838b3d753f8
Create Date: 2019-09-20 16:38:33.064728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c66718b9c411'
down_revision = 'c838b3d753f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('category', sa.String(length=100), nullable=True))
    op.execute("UPDATE product SET category= 'fiction'")
    op.alter_column('product', 'category', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'category')
    # ### end Alembic commands ###
